"""Writers for the ``results/*.txt`` files.

Every file states, at the top, what produced it and under which conventions, so
a number lifted into the manuscript carries its own audit trail.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from . import reproduction
from .schema import fmt, independence_key
from .stats import Spread, format_spread

RULE = "=" * 78
THIN = "-" * 78


def _wrap(text: str, width: int) -> list[str]:
    """Wrap a paragraph, collapsing the newlines a YAML block scalar leaves behind."""
    import textwrap

    return textwrap.wrap(" ".join(str(text).split()), width=width) or [""]


def header(title: str, subtitle: str = "", seed: int | None = None) -> list[str]:
    lines = [title, RULE]
    if subtitle:
        lines.append(subtitle)
    lines.append(f"generated by reproduce.py on {date.today().isoformat()}"
                 + (f"; seed={seed}" if seed is not None else ""))
    lines.append("")
    return lines


# --------------------------------------------------------------------------
# Task 7 - study selection audit
# --------------------------------------------------------------------------

def study_selection_audit(dataset, tier_disagreements) -> str:
    meta = dataset.meta
    lines = header(
        "STUDY SELECTION AND DATA-EXTRACTION AUDIT",
        f"dataset version {meta.get('dataset_version', 'unknown')} "
        f"({len(dataset)} records)",
    )

    lines += [
        "1. HOW THE EVIDENCE SET WAS ASSEMBLED",
        THIN,
        f"  systematic search claimed : {fmt(meta.get('is_systematic_search'))}",
        f"  search sources            : {fmt(meta.get('search_sources'))}",
        f"  search period             : {fmt(meta.get('search_period'))}",
        f"  search strings            : {fmt(meta.get('search_strings'))}",
        f"  date compiled             : {fmt(meta.get('date_compiled'))}",
        "",
        "  This is a CURATED EVIDENCE SET, not a systematic review. The identification",
        "  and screening process was not recorded when the dataset was assembled, so a",
        "  PRISMA-style flow of identified / screened / included / excluded counts",
        "  cannot be reported. The counts below describe the dataset as it now stands,",
        "  which is not the same thing.",
        "",
        "2. FLOW (what is genuinely known)",
        THIN,
    ]
    n = len(dataset)
    n_cost = sum(1 for r in dataset if r.has_cost)
    n_gwp = sum(1 for r in dataset if r.has_published_gwp)
    n_b = sum(1 for r in dataset if r.reconstructability_tier == "B")
    n_exec = sum(1 for r in dataset if r.is_executable)
    lines += [
        f"  records in dataset                    : {n}",
        f"  identified / screened / excluded before inclusion : unknown (not recorded)",
        f"  reporting an economic value           : {n_cost}",
        f"  reporting a published GWP endpoint    : {n_gwp}",
        f"  declared Tier B                       : {n_b}",
        f"  executable by the engine today        : {n_exec}",
        "",
        "3. TIER RULE AND DISAGREEMENTS",
        THIN,
        "  Tier B requires ALL of: a published foreground inventory, published CAPEX or",
        "  OPEX information, and a scenario builder registered in",
        "  paper/reconstructions.py. Anything else is Tier A - a literature point that",
        "  may enter descriptive statistics but not a mechanistic reconstruction.",
        "",
    ]
    if tier_disagreements:
        lines.append("  Studies whose declared tier is not supported by the evidence:")
        for sid, declared, rule in tier_disagreements:
            lines.append(f"    {sid:26s} declared={declared}  rule={rule}")
        lines.append("")
    else:
        lines.append("  No disagreement between declared tier and the rule.\n")

    lines += [
        "4. EVIDENCE CLASS AND DECLARED DEPENDENCIES",
        THIN,
        "  What each comparison DEPENDS ON, not how well it did. None of these records",
        "  is a prospective validation: every target was published before its scenario",
        "  was built, which is why no class is called 'blind'. Records sharing an",
        "  independence group are several scenarios of ONE publication, facility model",
        "  and author group.",
        "",
        f"  {'study_id':26s} {'evidence class':22s} {'overlap':>7s}  independence group",
    ]
    for r in sorted(dataset, key=lambda r: r.study_id):
        if (r.evidence_class or "none") == "none":
            continue
        lines.append(
            f"  {r.study_id:26s} {fmt(r.evidence_class):22s} "
            f"{fmt(r.author_overlap_with_algametrix):>7s}  {independence_key(r)}"
        )
    lines.append("")
    shared = {}
    for r in dataset:
        if (r.evidence_class or "none") != "none":
            shared.setdefault(independence_key(r), []).append(r.study_id)
    multi = {k: v for k, v in shared.items() if len(v) > 1}
    if multi:
        lines.append("  Groups contributing more than one comparison - counted as one source:")
        for key, ids in sorted(multi.items()):
            lines.append(f"    {key:36s} {', '.join(sorted(ids))}")
        lines.append("")
    any_dep = False
    for r in sorted(dataset, key=lambda r: r.study_id):
        for d in r.dependency_notes:
            any_dep = True
            lines.append(f"  [{r.study_id}] {d}")
    if not any_dep:
        lines.append("  no dependency recorded on any record")
    lines.append("")

    lines += ["5. PER-STUDY RECORD", THIN,
              f"  {'study_id':26s} {'tier':4s} {'compl.':>7s}  {'exec':>5s}  citation"]
    for r in sorted(dataset, key=lambda r: r.study_id):
        lines.append(
            f"  {r.study_id:26s} {fmt(r.reconstructability_tier):4s} "
            f"{r.completeness():7.0%}  {'yes' if r.is_executable else 'no':>5s}  "
            f"{r.full_citation[:60]}"
        )
    lines.append("")

    lines += ["6. PROVENANCE AND TRACEABILITY GAPS", THIN,
              "  Provenance (identified source) is REQUIRED to enter any main result.",
              "  Traceability (DOI and the value's location inside the source) is not",
              "  required, but every gap is listed so it is visible.",
              ""]
    any_gap = False
    for r in sorted(dataset, key=lambda r: r.study_id):
        gaps = r.missing_provenance()
        if gaps:
            any_gap = True
            lines.append(f"  {r.study_id:26s} NO PROVENANCE: missing {', '.join(gaps)}")
    if not any_gap:
        lines.append("  provenance: complete for every record")
    n_trace = 0
    for r in sorted(dataset, key=lambda r: r.study_id):
        gaps = r.missing_traceability()
        if gaps:
            n_trace += 1
            lines.append(f"  {r.study_id:26s} traceability gap: {', '.join(gaps)}")
    lines += [f"  {n_trace} of {len(dataset)} records lack full traceability metadata.", ""]

    lines += ["7. OPEN TODOs FROM MISSING SOURCE INFORMATION", THIN]
    total = 0
    for r in sorted(dataset, key=lambda r: r.study_id):
        for t in r.todos:
            total += 1
            lines.append(f"  [{r.study_id}] {t}")
    if not total:
        lines.append("  none")
    lines += ["", f"  total open TODOs: {total}", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Task 2 - economic endpoint audit
# --------------------------------------------------------------------------

def _definition_audit_block(defn, indent: str = "  ") -> list[str]:
    """How far the cohort's homogeneity is verified rather than merely declared."""
    from .endpoints import ENDPOINT_DEFINITION_FIELDS

    lines = [
        "ENDPOINT-DEFINITION COMPLETENESS OF THE COHORT",
        THIN,
        f"{indent}Screening on endpoint type and functional unit makes the cohort uniform in",
        f"{indent}its LABEL. Whether the underlying numbers are the same quantity depends on",
        f"{indent}the attributes below, study by study.",
        "",
        f"{indent}{'attribute':30s} {'known':>8s} {'unknown':>8s}",
    ]
    for f in ENDPOINT_DEFINITION_FIELDS:
        k = defn.known.get(f, 0)
        lines.append(f"{indent}{f:30s} {k:8d} {defn.n - k:8d}")
    lines += ["", f"{indent}{'study_id':26s} attributes still unknown"]
    for sid, missing in sorted(defn.unknown_by_study.items()):
        lines.append(f"{indent}{sid:26s} {', '.join(missing) if missing else '(none)'}")
    lines += ["", f"{indent}VERDICT"]
    for s in defn.statement():
        lines.append(f"{indent}  {s}")
    lines.append("")
    return lines


def economic_endpoint_audit(dataset, audits, breakdown, primary_definition,
                            definition=None) -> str:
    lines = header(
        "ECONOMIC ENDPOINT AUDIT",
        "which economic quantity each study reports, and whether it may enter the "
        "primary production-cost comparison",
    )
    lines += ["PRIMARY ENDPOINT", THIN, f"  {primary_definition}", ""]

    lines += ["LITERATURE STATISTICS BY ENDPOINT TYPE (not pooled)", THIN]
    for etype, ids in sorted(breakdown.items()):
        lines.append(f"  {etype:32s} n={len(ids):2d}  {', '.join(ids)}")
    lines.append("")

    lines += [
        "PER-STUDY CLASSIFICATION",
        THIN,
        f"  {'study_id':26s} {'source metric':28s} {'classification':30s} "
        f"{'eligible':8s} reason",
    ]
    for a in audits:
        lines.append(
            f"  {a.study_id:26s} {(a.source_metric or 'unknown')[:28]:28s} "
            f"{a.classification:30s} {'yes' if a.eligible else 'NO':8s} "
            f"{a.exclusion_reason or ''}"
        )
    lines.append("")

    lines += ["CAVEATS ON INCLUDED STUDIES (endpoint definition not fully verified)", THIN]
    any_caveat = False
    for a in audits:
        if a.eligible and a.caveats:
            any_caveat = True
            lines.append(f"  {a.study_id:26s} {'; '.join(a.caveats)}")
    if not any_caveat:
        lines.append("  none")
    lines.append("")

    if definition is not None:
        lines += _definition_audit_block(definition)

    n_elig = sum(1 for a in audits if a.eligible)
    lines += [
        "SUMMARY",
        THIN,
        f"  studies with an economic value : {sum(1 for a in audits if a.source_metric)}",
        f"  eligible for the primary spread: {n_elig}",
        f"  excluded                       : {sum(1 for a in audits if not a.eligible)}",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Task 1 + 3 - harmonization
# --------------------------------------------------------------------------

def harmonization(a, b, conclusion_lines, registry, definition=None) -> str:
    lines = header(
        "COST HARMONIZATION",
        "two formally separate analyses, each on a cohort that does not change "
        "between its own stages",
    )

    lines += [
        "READ THIS FIRST",
        THIN,
        "  Analysis A and Analysis B are NOT two steps of one chain. A measures the",
        "  effect of currency and price-year conversion over the full eligible literature",
        "  cohort. B measures the effect of imposing a common accounting profile over the",
        "  much smaller cohort the engine can execute. The spread in A and the spread in B",
        "  describe different populations and must never be quoted as a sequence.",
        "",
    ]

    # ---------------- Analysis A ----------------
    from .endpoints import PRIMARY_COHORT_LABEL

    lines += [RULE, "FULL LITERATURE COHORT (Analysis A)", RULE,
              f"  cohort n = {len(a.cohort)}; identical at stage A1 and A2",
              f"  what it is: {PRIMARY_COHORT_LABEL}",
              f"  members  : {', '.join(a.cohort.ids)}", ""]
    if definition is not None:
        for s in definition.statement():
            lines.append(f"  {s}")
        lines.append("")
    lines.append(format_spread(a.stage_common_currency, "EUR/kg"))
    lines.append("")
    lines.append(format_spread(a.stage_price_normalized, "EUR/kg"))
    lines.append("")
    lines += ["  ROBUSTNESS TO THE COST SPLIT", THIN,
              "  No study in the cohort publishes a CAPEX/OPEX breakdown, so the split used",
              "  to weight the per-class indices is taken from the engine's own executable",
              "  reconstructions and the result is reported as an interval over them."]
    if a.shares is not None:
        lines += a.shares.as_lines()
    lines.append("")
    for key in ("lower", "upper", "legacy"):
        lines.append(format_spread(a.bounds_spreads[key], "EUR/kg"))
        lines.append("")

    lines += ["  PER-STUDY TRANSFORMATION AUDIT", THIN]
    for sid in a.cohort.ids:
        n = a.normalizations[sid]
        lines.append(
            f"    {sid:26s} {fmt(n.source_value):>10s} {fmt(n.source_currency)} "
            f"{fmt(n.source_price_year)}  ->  {n.value:,.4g} "
            f"{n.target_currency} {n.target_price_year}"
        )
        lines += n.audit_lines()
    lines.append("")

    if a.excluded:
        lines += ["  EXCLUDED FROM THIS COHORT", THIN]
        for sid, reason in a.excluded:
            lines.append(f"    {sid:26s} {reason}")
        lines.append("")

    # ---------------- Analysis B ----------------
    from .harmonization import independence_audit

    lines += [RULE, "MATCHED RECONSTRUCTABLE COHORT (Analysis B)", RULE,
              f"  cohort n = {b.n}; identical at stages B1, B2 and B3",
              f"  members  : {', '.join(b.cohort.ids) if b.n else '(none)'}", ""]
    if b.n:
        ind = independence_audit(b.cohort)
        lines += ["  INDEPENDENCE OF THE EVIDENCE", THIN,
                  f"    records          : {ind.n}",
                  f"    publications     : {ind.n_publications}",
                  f"    external to us   : {ind.n_external}",
                  f"    authors' own     : {', '.join(ind.self_cited) or 'none'}",
                  f"    overlap unknown  : {', '.join(ind.overlap_unknown) or 'none'}"]
        for doi, ids in sorted(ind.publications.items()):
            lines.append(f"      {doi:44s} {', '.join(ids)}")
        for s in ind.statement():
            lines.append(f"    {s}")
        lines.append("")
    if b.blocked:
        lines += ["  BLOCKED - declared Tier B, eligible on endpoint, but not executable:"]
        for sid, why in sorted(b.blocked.items()):
            lines.append(f"    {sid:26s} {why}")
        lines.append("")
    if b.basis_blocked:
        lines += ["  DROPPED - executable, but the engine output cannot be expressed in the",
                  "  common basis, so pooling it would repeat the currency-mixing defect:"]
        for sid, why in sorted(b.basis_blocked.items()):
            lines.append(f"    {sid:26s} {why}")
        lines.append("")
    lines += ["  COMMON ACCOUNTING PROFILE"] + b.profile.as_lines() + [""]

    if b.engine_transfers:
        lines += [
            "  PRICE BASIS OF THE ENGINE OUTPUTS",
            THIN,
            "    The engine returns a cost in the units of the price set it was fed. Stages",
            "    B2 and B3 are therefore transformed to the common basis before pooling; "
            "    without this the spread would mix currencies and price years.",
            f"    {'study_id':26s} {'engine basis':16s} {'kind':26s} transformation",
        ]
        for sid in b.cohort.ids:
            tr = b.engine_transfers.get(sid)
            if tr is None:
                continue
            lines.append(
                f"    {sid:26s} {tr.from_basis.label:16s} {tr.from_basis.kind:26s} "
                f"{tr.quality}"
                + (f" (x{tr.amount_out / tr.amount_in:.4f})"
                   if tr.amount_in and not tr.is_identity else "")
            )
            if tr.from_basis.is_mixed:
                lines.append(
                    f"      {'':24s} MIXED price set: "
                    f"{len(tr.from_basis.library_priced)} price(s) left at the shipped "
                    "library default, so this value is not purely in the declared currency"
                )
        lines.append("")

    if b.n:
        for sp in (b.stage_source_value, b.stage_source_accounting, b.stage_common_accounting):
            lines.append(format_spread(sp, "EUR/kg"))
            lines.append("")
        lines += ["  PAIRED STUDY-LEVEL CHANGE, source accounting -> common accounting", THIN,
                  f"    {'study_id':26s} {'source acc.':>12s} {'common acc.':>12s} "
                  f"{'abs':>10s} {'rel':>8s}"]
        for p in b.paired:
            rel = f"{p.relative:+.1%}" if p.relative is not None else "n/a"
            lines.append(
                f"    {p.study_id:26s} {p.before:12,.4g} {p.after:12,.4g} "
                f"{p.absolute:+10,.4g} {rel:>8s}"
            )
        lines.append("")
    else:
        lines += ["  No study in the dataset is both endpoint-eligible and executable.",
                  "  Analysis B cannot be run.", ""]

    lines += [RULE, "CONCLUSION (auto-generated, conditional)", RULE]
    for c in conclusion_lines:
        lines.append("  " + c)
    lines.append("")

    lines += ["INDEX PROVENANCE", THIN]
    for name, idx in sorted(registry.indices.items()):
        lines.append(
            f"  {name:22s} class={idx.normalization_class:14s} "
            f"available={'yes' if idx.available else 'NO':3s} "
            f"provenance={idx.provenance}"
        )
        if idx.source:
            lines.append(f"    source: {idx.source}")
        lines.append(f"    retrieval_date: {fmt(idx.retrieval_date)}")
        for t in idx.todos:
            lines.append(f"    TODO: {t}")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Task 4 + 8 - GWP populations
# --------------------------------------------------------------------------

def gwp_harmonization(p, conclusion_lines, class_disagreements) -> str:
    lines = header(
        "GWP ANALYSIS POPULATIONS",
        "published evidence, engine reproductions of published evidence, and "
        "model-derived extensions - kept apart",
    )

    lines += [RULE, "PUBLISHED GWP LITERATURE SET", RULE,
              f"  n = {p.n_published}", ""]
    lines.append(format_spread(p.published_spread_net, "kg CO2-eq/kg"))
    lines += ["", "  by analysis class:"]
    for cls, ids in sorted(p.published_by_class.items()):
        lines.append(f"    {cls:44s} n={len(ids):2d}  {', '.join(ids)}")
    lines.append("")
    lines += [f"  {'study_id':26s} {'published GWP':>13s}  system"]
    for r in p.published_literature:
        lines.append(
            f"  {r.study_id:26s} {fmt(r.reported_gwp):>13s}  "
            f"{fmt(r.cultivation_system)}"
        )
    lines.append("")

    lines += [RULE, "GWP-REPRODUCED MATCHED SET", RULE,
              "  Only studies with an actual published GWP endpoint that the engine can "
              "execute.",
              f"  n = {p.n_reproduced}", ""]
    if p.blocked:
        lines += ["  BLOCKED - published GWP, declared Tier B, not executable:"]
        for sid, why in sorted(p.blocked.items()):
            lines.append(f"    {sid:26s} {why}")
        lines.append("")
    if p.reproduced_cases:
        lines.append(_case_table(p.reproduced_cases))
        lines.append("")
        for sp in (p.reproduced_spread_native_gross, p.reproduced_spread_common_gross):
            if sp is not None:
                lines.append(format_spread(sp, "kg CO2-eq/kg"))
                lines.append("")
    else:
        lines += ["  No case in this set.", ""]

    lines += [RULE, "FULL EXECUTABLE FOREGROUND SET", RULE,
              "  Every scenario the engine can run. Cases labelled "
              "'model_derived_gwp_from_tea_scenario'",
              "  come from studies that published no GWP: they are model output, not "
              "validation.",
              f"  n = {len(p.executable_cases)}", ""]
    lines.append(_case_table(p.executable_cases))
    lines.append("")
    lines += [f"  common background applied: {p.background.name} "
              f"(elec {p.background.elec_gwp:g} kg CO2-eq/kWh, "
              f"heat {p.background.heat_gwp:g} kg CO2-eq/MJ; {p.background.source})", ""]
    for sp in (p.executable_spread_native_gross, p.executable_spread_common_gross,
               p.executable_spread_native_net, p.executable_spread_common_net):
        lines.append(format_spread(sp, "kg CO2-eq/kg"))
        lines.append("")

    if class_disagreements:
        lines += ["  DECLARED vs RULE-DERIVED ANALYSIS CLASS", THIN]
        for sid, declared, rule in class_disagreements:
            lines.append(f"    {sid:26s} declared={declared}  rule={rule}")
        lines.append("")

    lines += [RULE, "CONCLUSION (auto-generated, conditional)", RULE]
    for c in conclusion_lines:
        lines.append("  " + c)
    lines.append("")
    return "\n".join(lines)


def _case_table(cases) -> str:
    head = (
        f"  {'study_id':24s} {'analysis class':38s} {'elec':>7s} "
        f"{'nat.CF':>7s} {'com.CF':>7s} {'grossN':>8s} {'adjN':>8s} {'netN':>8s} "
        f"{'grossC':>8s} {'netC':>8s} {'publ.':>7s}"
    )
    rows = [head, "  " + THIN]
    for c in cases:
        rows.append(
            f"  {c.study_id:24s} {c.analysis_class:38s} {c.elec_kwh_per_kg:7.2f} "
            f"{c.native_elec_gwp:7.3f} {c.common_elec_gwp:7.3f} "
            f"{c.native_gross:8.3f} {c.native_adjustment:8.3f} {c.native_net:8.3f} "
            f"{c.common_gross:8.3f} {c.common_net:8.3f} "
            f"{(f'{c.published_gwp:.2f}' if c.published_gwp is not None else '-'):>7s}"
        )
    rows.append("  (N = native background, C = common background; adj = biogenic-carbon "
                "adjustment)")
    for c in cases:
        for n in c.notes:
            rows.append(f"    [{c.study_id}] {n}")
    return "\n".join(rows)


# --------------------------------------------------------------------------
# Task 8 - carbon accounting
# --------------------------------------------------------------------------

def carbon_accounting(reports, spreads) -> str:
    from .carbon import format_carbon_report

    lines = header(
        "BIOGENIC-CARBON ACCOUNTING",
        "gross GWP, carbon flows and net GWP under every convention, for every "
        "executable scenario",
    )
    lines += [
        "CONVENTIONS",
        THIN,
        "  no_biogenic_credit              no adjustment; gross == net",
        "  source_specific_credit          credit CO2-fed carbon only (engine default;",
        "                                  credits carbon fixed by the GROSS biomass)",
        "  temporary_storage_credit_at_gate credit the carbon that leaves the gate in the",
        "                                  product, whatever fed it",
        "",
    ]
    for r in reports:
        lines.append(format_carbon_report(r))
        lines.append("")

    lines += [RULE, "SPREAD STATISTICS UNDER EACH CONVENTION", RULE,
              "  Ratios are never computed across zero: see each block's ratio convention.",
              ""]
    for sp in spreads:
        lines.append(format_spread(sp, "kg CO2-eq/kg"))
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Reproductions (replaces the legacy validation.txt / lca_validation.txt)
# --------------------------------------------------------------------------

def reproductions(rows, blocked, excluded=None) -> str:
    lines = header(
        "ENGINE REPRODUCTIONS VERSUS SOURCE VALUES",
        "point reproductions, range plausibility checks and endpoint mismatches, "
        "kept apart",
    )
    lines += [
        "HOW TO READ THIS",
        THIN,
        "  A deviation is only meaningful when the engine output and the source value are",
        "  the SAME economic or environmental endpoint AND are expressed in the SAME",
        "  currency and price year. Rows marked 'endpoint mismatch' are not compared.",
        "  Rows marked 'range' are plausibility checks against a published envelope, not",
        "  point predictions, and are never converted to a percentage deviation from an",
        "  envelope midpoint. Rows marked 'NOT COMPARABLE' carry no percentage at all.",
        "",
        "  AlgaMetrix has no currency of its own: it returns a cost in the units of the",
        "  price set it was fed. Each row therefore states the basis of the engine value,",
        "  the basis of the source value, and any transformation between them. Where a",
        "  scenario mixes source prices with shipped library defaults, it is run a second",
        "  time with those defaults expressed in the source's currency and the deviation",
        "  is given as the interval the two readings span.",
        "",
        f"  {'study_id':24s} {'metric':6s} {'evidence class':22s} {'kind':10s} "
        f"{'model':>10s} {'source':>10s} {'basis':14s} verdict",
    ]
    for r in rows:
        model = f"{r.model:,.4g}" if r.model is not None else "n/a"
        ref = f"{r.reference:,.4g}" if r.reference is not None else "n/a"
        lines.append(
            f"  {r.study_id:24s} {r.metric:6s} {r.evidence_class:22s} "
            f"{r.comparison_kind:10s} {model:>10s} {ref:>10s} {r.basis_label:14s} "
            f"{r.verdict}"
        )
        lines.append(f"      endpoint: {r.endpoint}")
        if r.raw_reference is not None:
            lines.append(f"      source  : {r.raw_reference:,.6g} as published; "
                         f"{r.reference:,.6g} after endpoint harmonization")
        if r.independence_group:
            lines.append(f"      group   : {r.independence_group}")
        for d in r.dependencies:
            lines.append(f"      depends : {d}")
        if r.engine_basis is not None:
            lines.append(f"      engine  : {r.engine_basis.label} [{r.engine_basis.kind}]"
                         + (f" - {r.engine_basis.provenance}"
                            if r.engine_basis.provenance else ""))
        if r.transfer is not None and not r.transfer.is_identity:
            lines += r.transfer.audit_lines()
        if r.model_alt is not None:
            lines.append(f"      bracket : {r.model_low:,.4g} - {r.model_high:,.4g} "
                         f"{r.basis_label} over the two currency readings")
        for n in r.notes:
            lines.append(f"      note    : {n}")
    lines.append("")

    summary = reproduction.evidence_summary(rows)
    n_point = summary.n_point
    n_range = sum(1 for r in rows if r.comparison_kind == "range")
    n_native = sum(1 for r in rows if r.metric == "cost" and r.transfer is not None
                   and r.transfer.is_identity)
    n_conv = sum(1 for r in rows if r.metric == "cost" and r.transfer is not None
                 and r.transfer.ok and not r.transfer.is_identity)
    n_mixed = sum(1 for r in rows if r.model_alt is not None)
    lines += [
        "SUMMARY",
        THIN,
        "  Classes are NEVER pooled. Only a retrospective untuned row is a comparison",
        "  the source's own reported endpoint did not feed; a component-informed or a",
        "  calibrated row borrows part of its target and is reported on its own.",
        "",
    ] + [f"  {line}" for line in summary.statement()] + [
        "",
        f"  range plausibility checks  : {n_range}",
        f"  not comparable             : {sum(1 for r in rows if r.comparison_kind not in ('point', 'range'))}",
        "",
        "  PRICE BASIS OF THE COST COMPARISONS",
        f"    compared in the source's own basis, no conversion : {n_native}",
        f"    engine value converted into the source's basis    : {n_conv}",
        f"    mixed price set, deviation reported as an interval: {n_mixed}",
        "",
        "NOT REPRODUCIBLE - declared Tier B, scenario definition absent from the repository",
        THIN,
    ]
    if blocked:
        for sid, why in sorted(blocked.items()):
            lines.append(f"  {sid:26s} legacy result: {why}")
    else:
        lines.append("  none")
    lines += [
        "",
        "EXCLUDED - withdrawn from every population, with the reason",
        THIN,
        "  These records are kept in the dataset rather than deleted, so that an exclusion",
        "  is countable and a reader can see what was taken out and why. Their scenario",
        "  builders still exist and still run: what was found unsound is the PUBLISHED",
        "  VALUE, not the reconstruction, and the scenarios remain in the software",
        "  verification suite.",
        "",
    ]
    if excluded:
        for sid, why in sorted(excluded.items()):
            lines.append(f"  {sid}")
            for chunk in _wrap(why, 74):
                lines.append(f"      {chunk}")
    else:
        lines.append("  none")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Task 5 - Sobol
# --------------------------------------------------------------------------

def sobol_validation(outcomes, salib_present: bool, tolerance: float,
                     group_outcomes=None) -> str:
    lines = header(
        "SOBOL IMPLEMENTATION VALIDATION",
        "synthetic benchmarks with analytical indices, plus an independent "
        "reference implementation",
        seed=outcomes[0].seed if outcomes else None,
    )
    lines += [
        "ESTIMATORS",
        THIN,
        "  S_i  = (1/N) sum f(B)[f(AB_i) - f(A)] / Var(Y)      Saltelli et al. 2010",
        "  ST_i = (1/2N) sum [f(A) - f(AB_i)]^2 / Var(Y)       Jansen",
        "  A and B: two halves of one scrambled Sobol' sequence in 2k dimensions.",
        "  Var(Y) over the pooled A and B outputs. N(k+2) evaluations.",
        "",
        "  The GROUP estimator (sobol.analyze_groups) is the same pair of formulas with a",
        "  whole block of columns swapped at a time, so S[G] = Var(E[Y|X_G])/Var(Y). It is",
        "  validated separately below, because its headline quantity - the remainder, i.e.",
        "  the variance carried by interactions BETWEEN groups - has no per-parameter",
        "  analogue and cannot be checked by the benchmarks above.",
        "",
        f"  reference library available: {'SALib' if salib_present else 'NO (not installed)'}",
        "  reproduce the cross-check with:  pip install SALib && python reproduce.py --only sobol",
        f"  documented tolerance on analytical indices: {tolerance:g} absolute",
        "",
    ]
    all_ok = True
    for o in outcomes:
        lines += [THIN, f"BENCHMARK: {o.benchmark}   N={o.n_base}  "
                        f"evaluations={o.result.n_evaluations}  seed={o.seed}", THIN]
        ref = o.reference
        has_ref = bool(ref) and "S1" in (ref or {})
        head = (f"  {'param':6s} {'S1 exact':>10s} {'S1 algam.':>10s} "
                f"{'S1 95% CI':>20s} {'S1 |err|':>9s}")
        if has_ref:
            head += f" {'S1 SALib':>10s}"
        lines.append(head)
        for i, name in enumerate(o.parameters):
            e = o.result.s1[i]
            row = (f"  {name:6s} {o.s1_exact[i]:10.4f} {e.value:10.4f} "
                   f"[{e.ci_low:+8.4f},{e.ci_high:+8.4f}] {o.s1_abs_error[i]:9.4f}")
            if has_ref:
                row += f" {ref['S1'][i]:10.4f}"
            lines.append(row)
        head = (f"  {'param':6s} {'ST exact':>10s} {'ST algam.':>10s} "
                f"{'ST 95% CI':>20s} {'ST |err|':>9s}")
        if has_ref:
            head += f" {'ST SALib':>10s}"
        lines.append(head)
        for i, name in enumerate(o.parameters):
            e = o.result.st[i]
            row = (f"  {name:6s} {o.st_exact[i]:10.4f} {e.value:10.4f} "
                   f"[{e.ci_low:+8.4f},{e.ci_high:+8.4f}] {o.st_abs_error[i]:9.4f}")
            if has_ref:
                row += f" {ref['ST'][i]:10.4f}"
            lines.append(row)
        ok = o.max_abs_error <= tolerance and not o.result.violations()
        all_ok = all_ok and ok
        lines += [f"  max absolute error : {o.max_abs_error:.4f}  -> "
                  f"{'PASS' if ok else 'FAIL'}",
                  f"  index violations   : {o.result.violations() or 'none'}",
                  f"  dropped rows       : {o.result.dropped_rows}",
                  f"  runtime            : {o.result.runtime_s:.2f} s", ""]
        if ref and "error" in ref:
            lines.append(f"  reference library error: {ref['error']}")
            lines.append("")

    for o in group_outcomes or []:
        lines += [
            THIN,
            f"GROUP BENCHMARK: {o.benchmark}   N={o.n_base}  "
            f"evaluations={o.result.n_evaluations}  seed={o.seed}",
            THIN,
            f"  {o.description}",
            "  partition: " + "; ".join(f"{g} = {{{', '.join(o.members[g])}}}"
                                        for g in o.groups),
            "",
            f"  {'group':6s} {'S exact':>10s} {'S algam.':>10s} "
            f"{'S 95% CI':>20s} {'S |err|':>9s}",
        ]
        for i, g in enumerate(o.groups):
            e = o.result.s[i]
            lines.append(f"  {g:6s} {o.s_exact[i]:10.4f} {e.value:10.4f} "
                         f"[{e.ci_low:+8.4f},{e.ci_high:+8.4f}] {o.s_abs_error[i]:9.4f}")
        lines.append(f"  {'group':6s} {'ST exact':>10s} {'ST algam.':>10s} "
                     f"{'ST 95% CI':>20s} {'ST |err|':>9s}")
        for i, g in enumerate(o.groups):
            e = o.result.st[i]
            lines.append(f"  {g:6s} {o.st_exact[i]:10.4f} {e.value:10.4f} "
                         f"[{e.ci_low:+8.4f},{e.ci_high:+8.4f}] {o.st_abs_error[i]:9.4f}")
        # The remainder is the quantity the group decomposition reports and the
        # only one with no per-parameter analogue, so it is checked explicitly.
        lines.append(f"  {'rest':6s} {o.interactions_exact:10.4f} "
                     f"{o.result.interactions:10.4f} {'':20s} "
                     f"{o.interactions_abs_error:9.4f}   "
                     "(variance carried by interactions BETWEEN groups)")
        ok = o.max_abs_error <= tolerance and not o.result.violations()
        all_ok = all_ok and ok
        lines += [f"  max absolute error : {o.max_abs_error:.4f}  -> "
                  f"{'PASS' if ok else 'FAIL'}",
                  f"  index violations   : {o.result.violations() or 'none'}",
                  f"  dropped rows       : {o.result.dropped_rows}",
                  f"  runtime            : {o.result.runtime_s:.2f} s", ""]

    lines += [RULE, f"OVERALL: {'PASS' if all_ok else 'FAIL'}", RULE, ""]
    return "\n".join(lines)


def sobol_convergence(blocks, criteria: dict) -> str:
    lines = header("SOBOL CONVERGENCE", "smallest sample size meeting declared criteria")
    lines += ["DECLARED CONVERGENCE CRITERIA", THIN]
    for k, v in criteria.items():
        lines.append(f"  {k:44s} {v}")
    lines.append("")
    for title, rows, chosen in blocks:
        lines += [THIN, title, THIN,
                  f"  {'N':>6s} {'evals':>8s} {'runtime':>8s} {'maxCIw':>8s} "
                  f"{'maxShift':>9s} {'rank==max':>10s} {'violations':>10s}"]
        for row in rows:
            lines.append(
                f"  {row.n_base:6d} {row.n_evaluations:8d} {row.runtime_s:8.2f} "
                f"{row.max_ci_width_dominant:8.4f} "
                f"{(row.max_abs_shift_vs_largest or 0):9.4f} "
                f"{str(row.ranking_matches_largest):>10s} "
                f"{len(row.result.violations()):10d}"
            )
        lines.append(f"  chosen: N={chosen.n_base}" if chosen else
                     "  chosen: NONE met the criteria at any tested size")
        if chosen:
            lines.append(f"  {'param':28s} {'S1':>8s} {'S1 95% CI':>20s} "
                         f"{'ST':>8s} {'ST 95% CI':>20s}")
            for name, s1, st in chosen.result.ranked():
                lines.append(
                    f"  {name:28s} {s1.value:8.4f} [{s1.ci_low:+8.4f},{s1.ci_high:+8.4f}] "
                    f"{st.value:8.4f} [{st.ci_low:+8.4f},{st.ci_high:+8.4f}]"
                )
        lines.append("")
    return "\n".join(lines)


def sensitivity(blocks, mode_descriptions, validation_passed: bool, seed: int) -> str:
    lines = header(
        "GLOBAL SENSITIVITY (SOBOL)",
        "total-order ST and first-order S1 with bootstrap 95% confidence intervals",
        seed=seed,
    )
    if not validation_passed:
        lines += ["!! THE IMPLEMENTATION VALIDATION DID NOT PASS. "
                  "These results must not be used. !!", ""]
    lines += ["SENSITIVITY MODES", THIN]
    for mode, desc in mode_descriptions.items():
        lines.append(f"  {mode:24s} {desc}")
    lines.append("")

    for block in blocks:
        lines += [RULE,
                  f"{block['archetype_label']}   [{block['archetype_kind']}]",
                  f"  provenance: {block['provenance']}", RULE]
        if block.get("archetype_notes"):
            lines.append(f"  note: {block['archetype_notes']}")
        for mode, results in block["modes"].items():
            lines.append(f"\n  MODE {mode}")
            for res in results:
                lines.append(
                    f"    {res.output}   (N={res.n_base}, {res.n_evaluations} evaluations, "
                    f"dropped={res.dropped_rows})"
                )
                lines.append(f"      {'parameter':28s} {'S1':>8s} {'S1 95% CI':>20s} "
                             f"{'ST':>8s} {'ST 95% CI':>20s}")
                for name, s1, st in res.ranked():
                    lines.append(
                        f"      {name:28s} {s1.value:8.4f} "
                        f"[{s1.ci_low:+8.4f},{s1.ci_high:+8.4f}] {st.value:8.4f} "
                        f"[{st.ci_low:+8.4f},{st.ci_high:+8.4f}]"
                    )
                if res.violations():
                    lines.append(f"      VIOLATIONS: {res.violations()}")
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Task 6 - uncertainty
# --------------------------------------------------------------------------

def uncertainty(blocks, convergence_blocks, parameter_metadata, seed: int, n_chosen: int,
                groups=None) -> str:
    """``groups`` maps ``(archetype_label, metric)`` to a ``GroupSobolResult``.

    The Monte-Carlo runs give the quantile *bands*; the variance *decomposition*
    comes from the group Sobol' analysis, because a conditional variance taken
    with the other groups pinned at nominal is not a variance decomposition of a
    non-additive model. Both are printed, the second explicitly as screening.
    """
    lines = header(
        "MONTE-CARLO UNCERTAINTY, SEPARATED BY SOURCE",
        f"triangular sampling, mode at nominal; n={n_chosen} chosen by convergence",
        seed=seed,
    )
    lines += [
        "HOW THE VARIANCE IS DECOMPOSED",
        THIN,
        "  Two different things are printed for each (archetype, metric) and they must",
        "  not be confused.",
        "",
        "  GROUP SOBOL' DECOMPOSITION - the decomposition used in the paper. S_G is",
        "  Var(E[Y|X_G])/Var(Y), the main effect of the group INCLUDING every interaction",
        "  among its own members; ST_G adds every interaction with parameters outside it.",
        "  First-order group indices sum to at most 1 and the remainder is the share of",
        "  variance carried by interactions BETWEEN groups. Nothing is assumed additive.",
        "  Estimated by the Saltelli/Jansen estimator with a whole block of columns",
        "  swapped at a time (sobol.analyze_groups), over UNIFORM supports.",
        "",
        "  CONDITIONAL-VARIANCE RATIOS - screening only. Each is the variance of one",
        "  Monte-Carlo run in which a single group varies and the others are PINNED at",
        "  their nominal values, divided by the joint variance. That is a slice through",
        "  the nominal point, not Var(E[Y|X_G]); the two coincide only for a model that",
        "  is additive in the groups. The ratios can sum to more or less than 1, they",
        "  depend on where the other groups were pinned, and the remainder is a leftover",
        "  rather than an interaction term. They are printed because the quantile bands",
        "  above come from the same runs and answer a legitimate what-if question.",
        "",
    ]
    lines += [
        "MODES",
        THIN,
        "  foreground_only       physical inventory parameters only",
        "  economic_only         prices, discount rate, labour, plant scale",
        "  lcia_background_only  characterization factors only",
        "  joint                 all of the above",
        "",
        "  Parameters are sampled INDEPENDENTLY. Grouped dependence is implemented but",
        "  switched off, because no correlation data exist for these systems. That is an",
        "  assumption, not a finding.",
        "",
    ]

    for block in blocks:
        lines += [RULE, f"{block['archetype_label']}   [{block['archetype_kind']}]",
                  f"  provenance: {block['provenance']}", RULE]
        if block.get("archetype_notes"):
            lines.append(f"  note: {block['archetype_notes']}")
        for metric, dec in block["metrics"].items():
            lines.append(f"\n  {metric}    nominal = {dec.joint.nominal:,.4g}")
            lines.append(f"    {'mode':22s} {'P10':>12s} {'P50':>12s} {'P90':>12s} "
                         f"{'P90/P10':>9s} {'abs band':>12s}")
            for mode, res in dec.results.items():
                ratio = f"{res.p90_p10:9.2f}" if res.p90_p10 is not None else "      n/a"
                lines.append(
                    f"    {mode:22s} {res.p10.value:12,.4g} {res.p50.value:12,.4g} "
                    f"{res.p90.value:12,.4g} {ratio} {res.absolute_band:12,.4g}"
                )
            lines.append(f"    {'quantile 95% CI':22s}")
            for mode, res in dec.results.items():
                lines.append(
                    f"      {mode:20s} P10[{res.p10.ci_low:,.4g}, {res.p10.ci_high:,.4g}] "
                    f"P50[{res.p50.ci_low:,.4g}, {res.p50.ci_high:,.4g}] "
                    f"P90[{res.p90.ci_low:,.4g}, {res.p90.ci_high:,.4g}]"
                )
            group = (groups or {}).get((block["archetype_label"], metric))
            if group is not None:
                lines.append(
                    "    GROUP SOBOL' DECOMPOSITION  Var(E[Y|X_G])/Var(Y), "
                    f"n_base={group.n_base}, {group.n_evaluations} evaluations:")
                lines.append(f"      {'group':24s} {'S':>9s} {'S 95% CI':>20s} "
                             f"{'ST':>9s} {'ST 95% CI':>20s}")
                for g, (s, st) in group.by_group().items():
                    lines.append(
                        f"      {g:24s} {s.value:9.4f} "
                        f"[{s.ci_low:+8.4f},{s.ci_high:+8.4f}] {st.value:9.4f} "
                        f"[{st.ci_low:+8.4f},{st.ci_high:+8.4f}]")
                lines.append(
                    f"      {'between-group interactions':24s} "
                    f"{group.interactions:9.4f}   (= 1 - sum of first-order group indices)")
                if group.violations():
                    lines.append(f"      !! {'; '.join(group.violations())}")
            lines.append(
                "    conditional-variance ratios (SCREENING ONLY - one group varying, the")
            lines.append(
                "    others PINNED at nominal; NOT a Sobol' decomposition, does not")
            lines.append(
                "    decompose the variance of a non-additive model, depends on where the")
            lines.append("    other groups were pinned):")
            for k, v in dec.conditional_variance_ratios().items():
                lines.append(f"      {k:24s} {('n/a' if v is None else f'{v:6.1%}'):>8s}")
            for mode, res in dec.results.items():
                for n in res.notes:
                    if "INDEPENDENT" in n:
                        continue
                    lines.append(f"    [{mode}] {n}")
        lines.append("")

    lines += [RULE, "QUANTILE CONVERGENCE", RULE]
    for title, rows, chosen in convergence_blocks:
        lines += [THIN, title, THIN,
                  f"  {'n':>7s} {'P10':>12s} {'P50':>12s} {'P90':>12s} {'P90/P10':>9s} "
                  f"{'maxRelShift':>12s} {'CIw(P90)':>10s}"]
        for row in rows:
            ratio = f"{row.p90_p10:9.2f}" if row.p90_p10 is not None else "      n/a"
            lines.append(
                f"  {row.n:7d} {row.p10:12,.4g} {row.p50:12,.4g} {row.p90:12,.4g} "
                f"{ratio} {(row.max_rel_shift_vs_largest or 0):12.4f} "
                f"{row.ci_width_p90:10,.4g}"
            )
        lines.append(f"  chosen: n={chosen.n}" if chosen else
                     "  chosen: NONE met the criteria; the largest tested n is used")
        lines.append("")

    lines += [RULE, "PARAMETER DISTRIBUTION METADATA", RULE,
              f"  {'parameter':28s} {'group':16s} {'dist':11s} {'lower':>12s} "
              f"{'mode':>12s} {'upper':>12s} {'evidence':22s} correlation group"]
    for md in parameter_metadata:
        lines.append(
            f"  {md['name']:28s} {md['group']:16s} {md['distribution']:11s} "
            f"{md['lower']:12,.4g} {md['mode_or_mean']:12,.4g} "
            f"{md['upper_or_sd']:12,.4g} {md['evidence_quality']:22s} "
            f"{md['correlation_group']}"
        )
        lines.append(f"      source: {md['source']}")
        if md.get("notes"):
            lines.append(f"      note  : {md['notes']}")
    lines.append("")
    return "\n".join(lines)
