#!/usr/bin/env python
"""Solve the AlgaMetrix LCA system with Brightway's ``bw2calc`` and compare.

This is the optional third leg of the implementation benchmark. The other two —
the sequential engine in :mod:`algametrix.lca` and the matrix implementation in
:mod:`algametrix.paper.matrixlca` — are both in this repository and both run in
CI. This script hands the *same* technosphere, biosphere and characterization
matrices to an independently written, widely used LCA solver.

It lives outside ``reproduce.py`` because ``bw2calc`` pulls in around thirty
packages that the engine does not otherwise need, and the repository should stay
installable without them. Run it in its own environment::

    python -m venv .bwenv
    .bwenv/bin/pip install bw2calc numpy pyyaml pandas   # Windows: .bwenv\\Scripts\\pip
    .bwenv/bin/python scripts/brightway_crosscheck.py

The output is written to ``results/brightway_crosscheck.txt`` and records the
``bw2calc`` version and interpreter that produced it, because a cross-check that
does not say what it ran against is not a cross-check.

What it verifies is the **linear solve**, not the model: Brightway is given
matrices assembled by this repository, so identical foreground data, functional
unit, boundaries and characterization factors. No background database is
involved, and none is needed — AlgaMetrix ships its own aggregated factors.
"""

from __future__ import annotations

import json
import platform
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from algametrix.library import load_library                        # noqa: E402
from algametrix.paper import matrixlca, suite                      # noqa: E402

OUT = ROOT / "results" / "brightway_crosscheck.txt"
RULE = "=" * 78
THIN = "-" * 78


def main() -> int:
    if not matrixlca.brightway_available():
        print("bw2calc is not importable in this interpreter.", file=sys.stderr)
        print(__doc__, file=sys.stderr)
        return 1

    import bw2calc

    lib = load_library()
    cases, _ = suite.distinct_cases(lib)

    rows = []
    worst = 0.0
    for case in cases:
        scn = case.scenario(lib)
        bw = matrixlca.compare_with_brightway(scn)
        ours = matrixlca.run_matrix_lca(scn).impacts
        per_cat = {
            cat: abs(value - ours[cat]) / max(abs(value), abs(ours[cat]), 1e-30)
            for cat, value in bw.items()
        }
        worst_cat = max(per_cat, key=per_cat.get)
        rows.append((case.key, case.label, bw, ours, per_cat[worst_cat], worst_cat))
        worst = max(worst, per_cat[worst_cat])

    ok = worst <= matrixlca.BENCHMARK_TOL
    nonzero = sum(1
                  for _k, _l, bw, ours, _m, _c in rows
                  for cat, value in bw.items()
                  if value != 0.0 or ours[cat] != 0.0)
    lines = [
        "BRIGHTWAY (bw2calc) CROSS-CHECK",
        RULE,
        "the AlgaMetrix technosphere, biosphere and characterization matrices, "
        "solved by an independently written LCA engine",
        f"generated by scripts/brightway_crosscheck.py on {date.today().isoformat()}",
        "",
        "WHAT THIS IS",
        THIN,
        "  bw2calc is given matrices assembled by this repository: identical foreground",
        "  data, identical functional unit, identical system boundaries, identical",
        "  characterization factors. What is compared is therefore the LINEAR SOLVE, not",
        "  the model. No background database is involved and none is needed - AlgaMetrix",
        "  ships its own aggregated cradle-to-gate factors, which is exactly why it does",
        "  not depend on Brightway for its results.",
        "",
        "  Agreement here means three independent implementations of the same",
        "  specification return the same numbers: the sequential accumulation in",
        "  algametrix.lca, the matrix implementation in algametrix.paper.matrixlca, and",
        "  bw2calc. It does not make any of them correct as a model of an algal plant.",
        "",
        "ENVIRONMENT",
        THIN,
        f"  bw2calc      : {bw2calc.__version__}",
        f"  python       : {platform.python_version()} ({platform.system()})",
        f"  numpy        : {__import__('numpy').__version__}",
        "",
        RULE,
        "RESULT",
        RULE,
        f"  scenarios cross-checked      : {len(rows)}",
        f"  indicator comparisons        : {sum(len(r[2]) for r in rows)}",
        # An indicator both engines return as zero agrees trivially. Counting
        # those separately keeps the headline from claiming more agreement than
        # was tested: a scenario whose source reported no water or no land
        # footprint has nothing for either solver to get wrong.
        f"  of which non-zero on both sides: {nonzero}",
        f"  maximum relative difference  : {worst:.3e}",
        f"  criterion                    : <= {matrixlca.BENCHMARK_TOL:g}",
        f"  overall                      : {'PASS' if ok else 'FAIL'}",
        "",
        f"  {'scenario':36s} {'max rel diff':>14s}  worst indicator",
    ]
    for key, _label, _bw, _ours, mx, cat in rows:
        lines.append(f"  {key:36s} {mx:14.2e}  {cat}")

    lines += ["", RULE, "PER-SCENARIO DETAIL", RULE]
    for key, label, bw, ours, _mx, _cat in rows:
        lines += [THIN, f"{key}  -  {label}", THIN,
                  f"  {'category':36s} {'matrixlca':>16s} {'bw2calc':>16s} {'rel':>10s}"]
        for cat, value in bw.items():
            denom = max(abs(value), abs(ours[cat]), 1e-30)
            lines.append(f"  {cat:36s} {ours[cat]:16.9g} {value:16.9g} "
                         f"{abs(value - ours[cat]) / denom:10.1e}")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # A companion machine-readable copy, so the figure code can plot the
    # cross-check without re-running it in an interpreter that has bw2calc.
    OUT.with_suffix(".json").write_text(json.dumps({
        "generated": date.today().isoformat(),
        "bw2calc_version": bw2calc.__version__,
        "python": platform.python_version(),
        "tolerance": float(matrixlca.BENCHMARK_TOL),
        "max_relative_difference": float(worst),
        "passed": bool(ok),
        "per_scenario": {key: float(mx) for key, _l, _b, _o, mx, _c in rows},
        "all_relative_differences": sorted(
            float(d)
            for _k, _l, bw, ours, _m, _c in rows
            for d in (
                abs(v - ours[c]) / max(abs(v), abs(ours[c]), 1e-30)
                for c, v in bw.items()
            )
        ),
    }, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  (max relative difference {worst:.3e})")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
